In [1]:
import pandas as pd

In [2]:
def load_fa(file_dir):
    with open(file_dir, 'r') as f:
        lines = f.readlines()
        
    te_dict = {}
    for l in lines:
        if l.startswith('>'):
            key = l[1:-1]
            ind = len(key.split('_')[0]) + key.split('_')[1].index('-') + 1
            id = key[:ind]
            tag = key[ind + 1: key.index('#')]
            te_class = key[key.index('#') + 1:]
        else:
            seq = l[:-1]
            te_dict[key] = {'key': key, 'id': id, 'tag': tag, 'class': te_class, 'seq': seq}
    
    return te_dict

In [3]:
vgp_te_dict = load_fa('../data/vgp/all_vgp_tes.fa')

In [11]:
with open('../data/vgp/features.txt', 'r') as f:
    lines = f.readlines()
    
    for l in lines:
        key, feature = l[1:-1].split('\t')
        if feature == "TRUE":
            vgp_te_dict[key]['feature'] = 1
        else:
            vgp_te_dict[key]['feature'] = 0

In [12]:
vgp_te_df = pd.DataFrame.from_dict(vgp_te_dict, orient='index', columns=['id', 'tag', 'class', 'seq', 'feature'])

In [13]:
vgp_te_df.iloc[:10]

,id,tag,class,seq,feature
hAT_1-aAnoBae#DNA/hAT,hAT_1,aAnoBae,DNA/hAT,TAGAGTTGAGCGCGGTTCGTGGTTCGTGGTTCTCCAGTTCGCGGCT...,1
hAT_131-aAnoBae#DNA/hAT,hAT_131,aAnoBae,DNA/hAT,TAGAGTTGAGCGCGGTTCGTGGTTCGTGGTTCTCCAGTTCGCGGCT...,1
hAT_147-aAnoBae#DNA/hAT,hAT_147,aAnoBae,DNA/hAT,TAGAGTTGAGCGCGGTTCGTGGTTCGTGGTTCTCCAGTTCGCGGCT...,0
hAT_210-aAnoBae#DNA/hAT,hAT_210,aAnoBae,DNA/hAT,TAGAGTTGAGCGCGGTTCGTGGTTCGTGGTTCTCCAGTTCGCGGCT...,0
hAT_254-aAnoBae#DNA/hAT,hAT_254,aAnoBae,DNA/hAT,TAGAGTTGAGCGCGGTTCGTGGTTCGTGGTTCTCCAGTTCGCGGCT...,0
ERV1_15-aAnoBae#LTR/ERV1,ERV1_15,aAnoBae,LTR/ERV1,TGTTGAGGATAAAGAATTGAGTATCCAAAAATACTTAATTCAGCCA...,0
hAT_292-aAnoBae#DNA/hAT,hAT_292,aAnoBae,DNA/hAT,TAGAGATGAGCGAACCGGTCCCGGTTCGGCTCGAGGCGGTTCGCCG...,0
hAT_298-aAnoBae#DNA/hAT,hAT_298,aAnoBae,DNA/hAT,TAGAGATGAGCGAACCGGTCCCGGTTCGGCTCGAGGCGGTTCGCCG...,0
hAT_299-aAnoBae#DNA/hAT,hAT_299,aAnoBae,DNA/hAT,TAGAGTTGAGCGCGGTTCGTGGTTCGTGGTTCTCCAGTTCGCGGCT...,0
PIF-Harbinger_1-aAnoBae#DNA/PIF-Harbinger,PIF-Harbinger_1,aAnoBae,DNA/PIF-Harbinger,AGGGGTGCTTCACACATAGCGAGATCGCTAGCGAGATCGCTGCTGA...,0

In [16]:
pd.to_pickle(vgp_te_df, '../data/vgp/vgp_te_features.pkl')

In [15]:
vgp_features = vgp_te_df[['seq', 'feature']].reset_index(drop=True)
vgp_features

                                                      seq  feature
0       TAGAGTTGAGCGCGGTTCGTGGTTCGTGGTTCTCCAGTTCGCGGCT...        1
1       TAGAGTTGAGCGCGGTTCGTGGTTCGTGGTTCTCCAGTTCGCGGCT...        1
2       TAGAGTTGAGCGCGGTTCGTGGTTCGTGGTTCTCCAGTTCGCGGCT...        0
3       TAGAGTTGAGCGCGGTTCGTGGTTCGTGGTTCTCCAGTTCGCGGCT...        0
4       TAGAGTTGAGCGCGGTTCGTGGTTCGTGGTTCTCCAGTTCGCGGCT...        0
...                                                   ...      ...
135746  GTTTTTGATCATAGATTTCATAGACTTTTTCATAGATTTTACAGTG...        0
135747  ATATTCAAAGACTTTTTTTTTTTAAATTTAGATTACCCAATTATTT...        0
135748  CTGGAATATCCATGATGTGAAGATGCCGGCGTTGGACTGGGGTGAG...        0
135749  CCCCACCTCCCAGGGGCTGGTTTAGCTCACNAGGGGCTGGTTTAGC...        0
135750  AATTTCTTGCAATGAAATGAAATGAGATGAAAATCGCTTATTGTCA...        0

[135751 rows x 2 columns]